#Accepted item IDs for NVG helmets (format: modid:item_name)
nvg_helmets = ["warborn:nato_sqad_leader_helmet", "warborn:nato_ukr_helmet", "warborn:nato_sqad_leader_helmet_woodland", "warborn:nato_ukr_helmet_woodland", "warborn:beta7_nvg_helmet", "warborn:beta7_nvg_helmet_slate", "warborn:beta7_nvg_helmet_ash"]
#Enable faceplate overlay cutout for helmets with the faceplate tag
enable_faceplate_overlay = false

